git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --syntax-theme="tomorrow-night"

gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side

  # vague
  # authorColors:
  #   "*": "#f3be7c"
  # theme:
  #   activeBorderColor:
  #     - "#aeaed1"
  #     - "bold"
  #   inactiveBorderColor:
  #     - "#606079"
  #   optionsTextColor:
  #     - "#606079"
  #   selectedLineBgColor:
  #     - "#252530"
  #   cherryPickedCommitFgColor:
  #     - "#d8647e"
  #   cherryPickedCommitBgColor:
  #     - "bg"
  #   markedBaseCommitFgColor:
  #     - "#f3be7c"
  #   markedBaseCommitBgColor:
  #     - "bg"
  #   unstagedChangesColor:
  #     - "#d8647e"
  #   defaultFgColor:
  #     - "#cdcdcd"

  # tomorrow night
  authorColors:
    "*": "#81a2be"
  theme:
    activeBorderColor:
      - "#81a2be"
      - "bold"
    inactiveBorderColor:
      - "#969896"
    optionsTextColor:
      - "#81a2be"
    selectedLineBgColor:
      - "#282a2e"
    cherryPickedCommitBgColor:
      - "#373b41"
    cherryPickedCommitFgColor:
      - "#81a2be"
    unstagedChangesColor:
      - "#cc6666"
    defaultFgColor:
      - "#c5c8c6"
    searchingActiveBorderColor:
      - "#f0c674"
