git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --syntax-theme="vague"

gui:
  authorColors:
    "*": "#f3be7c"
    # "*": "#fab283"
  theme:
    activeBorderColor:
      - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#606079"
    optionsTextColor:
      - "#606079"
    selectedLineBgColor:
      - "#252530"
    cherryPickedCommitFgColor:
      - "#d8647e"
    cherryPickedCommitBgColor:
      - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"

    # activeBorderColor:
    #   - "#9ebefb"
    #   - "bold"
    # inactiveBorderColor:
    #   - "#707070"
    # optionsTextColor:
    #   - "#707070"
    # selectedLineBgColor:
    #   - "#101010"
    # cherryPickedCommitFgColor:
    #   - "#fc533a"
    # cherryPickedCommitBgColor:
    #   - "bg"
    # markedBaseCommitFgColor:
    #   - "#fcd53a"
    # markedBaseCommitBgColor:
    #   - "bg"
    # unstagedChangesColor:
    #   - "#fc533a"
    # defaultFgColor:
    #   - "#ededed"
