git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --syntax-theme="Pierre Dark Soft"

gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side

  authorColors:
    "*": "#69b1ff"
  theme:
    activeBorderColor:
      - "#69b1ff"
      - "bold"
    inactiveBorderColor:
      - "#636363"
    optionsTextColor:
      - "#69b1ff"
    selectedLineBgColor:
      - "#1f3e5e"
    cherryPickedCommitBgColor:
      - "#2c2c2c"
    cherryPickedCommitFgColor:
      - "#69b1ff"
    unstagedChangesColor:
      - "#ff6762"
    defaultFgColor:
      - "#d4d4d4"
    searchingActiveBorderColor:
      - "#ffd452"
